import Head from 'next/head';
import CatalogManager from '../../components/admin/catalog/catalog-manager/catalog-manager.component';
import {
  adminTabs,
  applicationTabs,
  EAdminNavbarTabs,
  EAppNavbarTabs,
  HeaderTabs,
} from '../../components/common/header/app-header.component';

export default function Catalog() {
  return (
    <>
      <Head>
        <title>Управление Каталогом</title>
        <meta name="description"
              content="Generated by create next app" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1" />
        <link rel="icon"
              href="/favicon.ico" />
      </Head>
      <main>
        <HeaderTabs tabs={applicationTabs}
                    selectedTabId={EAppNavbarTabs.ADMIN} />
        <HeaderTabs tabs={adminTabs}
                    selectedTabId={EAdminNavbarTabs.CATALOG} />

        <CatalogManager />
      </main>
    </>
  );
}
