import { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import HomePageDesktopComponent from '../components/home/home-page-desktop.component';
import HomePageMobileComponent from '../components/home/home-page-mobile.component';
import { IPrimaryCatalog } from '../models/primary-catalog.model';
import { getRequestSSR } from '../utils/axios.utils';
import { IIsMobile, isMobile } from '../utils/device.utils';
import { getAuthServerSideProps, IWithUser } from '../utils/hooks/user.hook';

interface IPrimaryCatalogs extends IIsMobile, IWithUser {
  primaryCatalogs: IPrimaryCatalog[];
}

export const getServerSideProps = getAuthServerSideProps(
  async (c: GetServerSidePropsContext) => {
    return {
      props: {
        ...isMobile(c),
        primaryCatalogs: await getRequestSSR<IPrimaryCatalog[]>(c, 'catalog/primary'),
      },
    };
  },
  false,
);

export default function Home({ isMobile, primaryCatalogs }: IIsMobile & IPrimaryCatalogs) {
  return (
    <>
      <Head>
        <title>Ювелирка</title>
        <meta name="description"
              content="Generated by create next app" />
        <meta name="viewport"
              content="width=device-width, initial-scale=1" />
        <link rel="icon"
              href="/favicon.ico" />

      </Head>
      <main>
        {isMobile
          ? <HomePageMobileComponent primaryCatalogs={primaryCatalogs} />
          : <HomePageDesktopComponent primaryCatalogs={primaryCatalogs} />
        }
      </main>
    </>
  );
}
